# Generated by Django 5.0.6 on 2024-06-29 19:06

import barn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="cron",
            field=models.TextField(
                blank=True,
                help_text="Exactly 5 or 6 columns has to be specified for iterator expression",
                null=True,
                validators=[barn.models.validate_cron],
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
