# Generated by Django 5.0.7 on 2024-07-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="interval",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
