# Generated by Django 5.0.7 on 2024-07-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barn", "0002_schedule_interval"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "run_at"], name="barn_task_status_bddd9c_idx"
            ),
        ),
    ]
