# Generated by Django 5.0.7 on 2024-07-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barn", "0002_schedule_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="next_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="run_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(("status__in", ["D", "F"])),
                fields=["run_at"],
                name="barn_task_delete_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(("status", "Q")),
                fields=["run_at"],
                name="barn_task_find_next_idx",
            ),
        ),
    ]
