# Generated by Django 5.0.6 on 2024-06-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barn", "0002_alter_schedule_cron_alter_schedule_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lock",
            name="name",
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="lock",
            name="owner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="next_run_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
