# Generated by Django 5.0.7 on 2024-07-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barn", "0003_task_barn_task_find_next_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="next_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="run_at",
            field=models.DateTimeField(blank=True),
        ),
    ]
