# Generated by Django 5.0.6 on 2024-06-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barn", "0003_alter_lock_name_alter_lock_owner_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lock",
        ),
    ]
