# Generated by Django 5.0.6 on 2024-07-01 11:11

import barn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barn", "0004_delete_lock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="cron",
            field=models.CharField(
                blank=True,
                help_text="Exactly 5 or 6 columns has to be specified for iterator expression",
                max_length=200,
                null=True,
                validators=[barn.models.validate_cron],
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="func",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="func",
            field=models.CharField(max_length=1000),
        ),
    ]
