# Generated by Django 5.0.6 on 2024-06-30 11:52

import barn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cron",
                    models.TextField(
                        blank=True,
                        help_text="Exactly 5 or 6 columns has to be specified for iterator expression",
                        null=True,
                        validators=[barn.models.validate_cron],
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("arg1", models.IntegerField()),
                ("arg2", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Schedule2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cron",
                    models.TextField(
                        blank=True,
                        help_text="Exactly 5 or 6 columns has to be specified for iterator expression",
                        null=True,
                        validators=[barn.models.validate_cron],
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("arg1", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("is_success", models.BooleanField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("arg1", models.IntegerField()),
                ("arg2", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("is_success", models.BooleanField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("arg1", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
