# Generated by Django 5.0.6 on 2024-07-01 11:11

import barn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stall", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule1",
            name="cron",
            field=models.CharField(
                blank=True,
                help_text="Exactly 5 or 6 columns has to be specified for iterator expression",
                max_length=200,
                null=True,
                validators=[barn.models.validate_cron],
            ),
        ),
        migrations.AlterField(
            model_name="schedule2",
            name="cron",
            field=models.CharField(
                blank=True,
                help_text="Exactly 5 or 6 columns has to be specified for iterator expression",
                max_length=200,
                null=True,
                validators=[barn.models.validate_cron],
            ),
        ),
    ]
