# Generated by Django 5.0.6 on 2024-07-01 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stall", "0002_alter_schedule1_cron_alter_schedule2_cron"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task1",
            name="created",
        ),
        migrations.RemoveField(
            model_name="task2",
            name="created",
        ),
        migrations.AddField(
            model_name="task1",
            name="run_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task2",
            name="run_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
