# Generated by Django 5.0.6 on 2024-06-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lock",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lock",
            name="owner",
            field=models.TextField(blank=True, null=True),
        ),
    ]
