# Generated by Django 5.0.6 on 2024-06-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lock", "0002_alter_lock_locked_at_alter_lock_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="cron",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="last_run_ts",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="next_run_ts",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
