# Generated by Django 5.0.6 on 2024-06-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lock", "0003_alter_schedule_cron_alter_schedule_last_run_ts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="args",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_success",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="result",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
