# Generated by Django 5.0.6 on 2024-06-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lock", "0005_rename_payload_schedule_args_schedule_func"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="last_run_ts",
            new_name="last_run_at",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="next_run_ts",
            new_name="next_run_at",
        ),
    ]
