# Generated by Django 5.0.6 on 2024-06-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lock", "0006_rename_last_run_ts_schedule_last_run_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Queue",
        ),
    ]
