# Generated by Django 5.0.7 on 2024-07-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stall", "0002_someschedule_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="someschedule",
            name="next_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sometask",
            name="run_at",
            field=models.DateTimeField(blank=True),
        ),
    ]
